#!/usr/bin/env python3
"""
Lirox HF BitsAndBytes API Server
Generated by scripts/compress_model.py
"""

import sys
import subprocess
import argparse

def install_dependencies():
    print("Checking dependencies...")
    try:
        import torch
        import transformers
        import bitsandbytes
        import flask
        print("Dependencies found.")
    except ImportError:
        print("Installing required Hugging Face & API libraries...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", "torch", "transformers", "bitsandbytes", "accelerate", "flask"])

def start_server(model_id, port=11435):
    install_dependencies()
    
    from flask import Flask, request, jsonify
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

    print(f"Loading {model_id} in 4-bit precision... (This may take a minute).")
    
    # Configure Quantization
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.float16
    )

    tokenizer = AutoTokenizer.from_pretrained(model_id)
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        device_map="auto",
        quantization_config=bnb_config
    )

    print(f"✅ Model loaded. Starting Lirox HF API Server on port {port}...")
    
    app = Flask(__name__)

    @app.route('/api/generate', methods=['POST'])
    def generate():
        data = request.json
        if not data or "prompt" not in data:
            return jsonify({"error": "Missing prompt"}), 400
            
        prompt = data["prompt"]
        max_tokens = data.get("options", {}).get("num_predict", 512)
        
        inputs = tokenizer(prompt, return_tensors="pt").to("cuda" if torch.cuda.is_available() else "cpu")
        
        # Generation
        with torch.no_grad():
            outputs = model.generate(
                **inputs, 
                max_new_tokens=max_tokens,
                pad_token_id=tokenizer.eos_token_id
            )
            
        # Decode only the newly generated tokens
        input_length = inputs.input_ids.shape[1]
        response_text = tokenizer.decode(outputs[0][input_length:], skip_special_tokens=True)
        
        return jsonify({"response": response_text})

    # Suppress flask startup messages to keep terminal clean
    import logging
    log = logging.getLogger('werkzeug')
    log.setLevel(logging.ERROR)
    
    app.run(host="127.0.0.1", port=port)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run HF model via local BitsAndBytes API server")
    parser.add_argument("--model", default="meta-llama/Llama-2-7b-hf", help="Hugging Face model ID")
    parser.add_argument("--port", type=int, default=11435, help="Port to run the API server on")
    args = parser.parse_args()

    start_server(args.model, args.port)
