"""Lirox v2.0.0 — Skills System

/add-skill generates Python code via LLM.
Skills are saved to data/skills/ and can be listed and executed.
"""
from __future__ import annotations

import importlib.util
import json
import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional

from lirox.config import SKILLS_DIR


class SkillsManager:
    """Manages user-created skills (Python callables generated by LLM)."""

    def __init__(self, skills_dir: str = None):
        self.skills_dir = Path(skills_dir or SKILLS_DIR)
        self.skills_dir.mkdir(parents=True, exist_ok=True)

    # ── List ──────────────────────────────────────────────────────────────────

    def list_skills(self) -> List[Dict[str, str]]:
        """Return all skills with their metadata."""
        skills = []
        for meta_file in sorted(self.skills_dir.glob("*.json")):
            try:
                with open(meta_file, encoding="utf-8") as f:
                    meta = json.load(f)
                skills.append(meta)
            except Exception:
                pass
        return skills

    # ── Add ───────────────────────────────────────────────────────────────────

    def add_skill(self, description: str) -> dict:
        """
        Generate a Python skill from the description via LLM.
        Returns {'success': True, 'name': ..., 'file': ...} or {'error': ...}
        """
        from lirox.utils.llm import generate_response, strip_code_fences

        prompt = (
            f"Generate a Python function for this task: {description}\n\n"
            "Requirements:\n"
            "- Function named `run(args: dict) -> str`\n"
            "- Include all necessary imports inside the function\n"
            "- Return a string result\n"
            "- Include a metadata dict at the top: NAME, DESCRIPTION, AUTHOR\n"
            "- Handle errors gracefully\n\n"
            "Return ONLY the Python code, no explanations."
        )
        code = generate_response(prompt)
        if not code or "Error:" in code[:20]:
            return {"error": f"LLM failed: {code}"}

        code = strip_code_fences(code, "python")

        # Extract name from code metadata or derive from description
        name = self._extract_skill_name(code, description)

        # Save skill files
        skill_file = self.skills_dir / f"{name}.py"
        meta_file  = self.skills_dir / f"{name}.json"

        try:
            skill_file.write_text(code, encoding="utf-8")
            meta = {
                "name":        name,
                "description": description,
                "file":        str(skill_file),
                "created_at":  __import__("datetime").datetime.now().isoformat(),
            }
            meta_file.write_text(json.dumps(meta, indent=2), encoding="utf-8")
            return {"success": True, "name": name, "file": str(skill_file)}
        except Exception as e:
            return {"error": f"Failed to save skill: {e}"}

    # ── Execute ───────────────────────────────────────────────────────────────

    def run_skill(self, name_or_index: str, args: Dict[str, Any] = None) -> str:
        """Execute a skill by name or 1-based index."""
        if args is None:
            args = {}

        # Resolve by index
        if name_or_index.isdigit():
            skills = self.list_skills()
            idx = int(name_or_index) - 1
            if idx < 0 or idx >= len(skills):
                return f"No skill at index {name_or_index}."
            name = skills[idx]["name"]
        else:
            name = name_or_index

        skill_file = self.skills_dir / f"{name}.py"
        if not skill_file.exists():
            return f"Skill '{name}' not found."

        try:
            spec   = importlib.util.spec_from_file_location(f"skill_{name}", skill_file)
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
            if not hasattr(module, "run"):
                return f"Skill '{name}' has no run() function."
            return str(module.run(args))
        except Exception as e:
            return f"Skill execution error: {e}"

    # ── Helpers ───────────────────────────────────────────────────────────────

    def _extract_skill_name(self, code: str, description: str) -> str:
        """Extract NAME from code metadata or derive a safe name from description."""
        # Look for NAME = "..." pattern
        m = re.search(r'NAME\s*=\s*["\']([^"\']+)["\']', code)
        if m:
            return re.sub(r"[^a-z0-9_]", "_", m.group(1).lower())[:40]
        # Derive from description
        words = re.sub(r"[^a-zA-Z0-9 ]", "", description).split()[:3]
        return "_".join(w.lower() for w in words) or "skill"

    def format_list(self) -> str:
        """Return a formatted string listing all skills."""
        skills = self.list_skills()
        if not skills:
            return "No skills yet. Use /add-skill <description> to create one."
        lines = ["Skills:\n"]
        for i, s in enumerate(skills, 1):
            lines.append(f"  {i}. {s['name']} — {s.get('description', '')[:60]}")
        return "\n".join(lines)
