"""Lirox v2.0.0 — Sub-Agents System

/add-agent generates a Python agent via LLM.
Agents are saved to data/agents/.
@name syntax routes messages directly to named agents.

BUG-6 FIX: Better @agentname extraction — handles spaces, colons, multiple names.
BUG-7 FIX: No 5-tier permission system. All agents have equal access.
BUG-8 FIX: Sub-agents receive full conversation context.
"""
from __future__ import annotations

import importlib.util
import json
import os
import re
from pathlib import Path
from typing import Dict, List, Optional

from lirox.config import AGENTS_DIR


class SubAgentsManager:
    """Manages user-created sub-agents (Python callables generated by LLM)."""

    def __init__(self, agents_dir: str = None):
        self.agents_dir = Path(agents_dir or AGENTS_DIR)
        self.agents_dir.mkdir(parents=True, exist_ok=True)

    # ── List ──────────────────────────────────────────────────────────────────

    def list_agents(self) -> List[Dict[str, str]]:
        agents = []
        for meta_file in sorted(self.agents_dir.glob("*.json")):
            try:
                with open(meta_file, encoding="utf-8") as f:
                    meta = json.load(f)
                agents.append(meta)
            except Exception:
                pass
        return agents

    # ── Add ───────────────────────────────────────────────────────────────────

    def add_agent(self, description: str) -> dict:
        """
        Generate a sub-agent from the description via LLM.
        Returns {'success': True, 'name': ..., 'file': ...} or {'error': ...}
        """
        from lirox.utils.llm import generate_response, strip_code_fences

        prompt = (
            f"Generate a Python sub-agent for this specialization: {description}\n\n"
            "Requirements:\n"
            "- Function named `respond(query: str, context: str = '') -> str`\n"
            "- Include all necessary imports inside the function\n"
            "- Include metadata: NAME, DESCRIPTION, SPECIALIZATION\n"
            "- The agent should use the context parameter (BUG-8 fix: full context)\n"
            "- Use lirox.utils.llm.generate_response for LLM calls\n"
            "- Handle errors gracefully\n\n"
            "Return ONLY the Python code."
        )
        code = generate_response(prompt)
        if not code or "Error:" in code[:20]:
            return {"error": f"LLM failed: {code}"}

        code = strip_code_fences(code, "python")

        # BUG-6 FIX: extract name from metadata or description properly
        name = self._extract_agent_name(code, description)

        agent_file = self.agents_dir / f"{name}.py"
        meta_file  = self.agents_dir / f"{name}.json"

        try:
            agent_file.write_text(code, encoding="utf-8")
            meta = {
                "name":          name,
                "description":   description,
                "file":          str(agent_file),
                "created_at":    __import__("datetime").datetime.now().isoformat(),
            }
            meta_file.write_text(json.dumps(meta, indent=2), encoding="utf-8")
            return {"success": True, "name": name, "file": str(agent_file)}
        except Exception as e:
            return {"error": f"Failed to save agent: {e}"}

    # ── Route ─────────────────────────────────────────────────────────────────

    def route_to_agent(self, agent_name: str, query: str,
                       full_context: str = "") -> str:
        """
        Route a query to a named sub-agent with full context.
        BUG-8 FIX: passes full_context so the agent has complete conversation history.
        """
        agent_file = self.agents_dir / f"{agent_name}.py"
        if not agent_file.exists():
            return f"Agent '{agent_name}' not found. Use /agents to list or /add-agent to create."

        try:
            spec   = importlib.util.spec_from_file_location(
                f"agent_{agent_name}", agent_file)
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
            if not hasattr(module, "respond"):
                return f"Agent '{agent_name}' has no respond() function."
            # BUG-8 FIX: pass full_context
            return str(module.respond(query, full_context))
        except Exception as e:
            return f"Agent error: {e}"

    # ── @name Extraction ──────────────────────────────────────────────────────

    @staticmethod
    def extract_agent_mention(text: str) -> Optional[tuple]:
        """
        Extract @agentname from the start of a message.

        BUG-6 FIX: Handles:
          @name query
          @name: query
          @name, query

        Returns (agent_name, remaining_query) or None.
        """
        # Match @word at the very start, possibly followed by :, ,, or space
        m = re.match(r"^@([\w-]+)[:\s,]*(.*)$", text.strip(), re.DOTALL)
        if m:
            agent_name = m.group(1).lower()
            query      = m.group(2).strip()
            return agent_name, query
        return None

    # ── Helpers ───────────────────────────────────────────────────────────────

    def _extract_agent_name(self, code: str, description: str) -> str:
        """BUG-6 FIX: Better name extraction from code metadata."""
        # Try NAME = "..."
        m = re.search(r'NAME\s*=\s*["\']([^"\']+)["\']', code)
        if m:
            raw = m.group(1)
        else:
            # Derive from first word(s) of description
            words = re.sub(r"[^a-zA-Z0-9 ]", "", description).split()[:2]
            raw = "_".join(words) if words else "agent"
        # Sanitize to valid Python/filename identifier
        return re.sub(r"[^a-z0-9_]", "_", raw.lower())[:40] or "agent"

    def format_list(self) -> str:
        agents = self.list_agents()
        if not agents:
            return "No agents yet. Use /add-agent <description> to create one."
        lines = ["Sub-Agents:\n"]
        for i, a in enumerate(agents, 1):
            lines.append(f"  {i}. @{a['name']} — {a.get('description', '')[:60]}")
        return "\n".join(lines)
