"""Lirox Autonomy — Code Tester.

Generates and runs unittest suites for Python snippets using only the stdlib.
No LLM calls are made here — test templates are rule-based.
"""
from __future__ import annotations

import ast
import sys
import tempfile
from pathlib import Path
from typing import Any, Dict, Generator, List

from lirox.autonomy.code_executor import CodeExecutor

_executor = CodeExecutor()

_TEST_TEMPLATE = '''
import unittest

# ── Code under test ──────────────────────────────────────────────────────────
{code}

# ── Generated tests ──────────────────────────────────────────────────────────
class AutoGeneratedTests(unittest.TestCase):
{test_methods}

if __name__ == "__main__":
    unittest.main()
'''

_DEFAULT_TEST_METHOD = '''\
    def test_module_imports_without_error(self):
        """The module-level code executes without raising an exception."""
        pass  # If the code block above imported cleanly, this passes.
'''


class CodeTester:
    """Generate lightweight unittest suites and execute them in a sandbox."""

    # ── Test generation ────────────────────────────────────────────────────

    def generate_tests(self, source: str) -> str:
        """Return a complete unittest source string for *source*.

        Uses simple heuristics to produce call-and-smoke tests for each
        top-level function / class found via AST.
        """
        methods: List[str] = []
        try:
            tree = ast.parse(source)
        except SyntaxError:
            return _TEST_TEMPLATE.format(
                code=source,
                test_methods=_DEFAULT_TEST_METHOD,
            )

        for node in tree.body:
            if isinstance(node, ast.FunctionDef):
                methods.append(self._fn_test(node))
            elif isinstance(node, ast.ClassDef):
                methods.append(self._class_test(node))

        if not methods:
            methods.append(_DEFAULT_TEST_METHOD)

        return _TEST_TEMPLATE.format(
            code=source,
            test_methods="\n".join(methods),
        )

    @staticmethod
    def _fn_test(fn: ast.FunctionDef) -> str:
        n_args = max(0, len(fn.args.args) - 1)  # exclude `self` if present
        call   = f"{fn.name}({', '.join('None' for _ in range(n_args))})"
        return (
            f"    def test_{fn.name}_callable(self):\n"
            f"        \"\"\"Smoke-test: {fn.name} can be called without crash.\"\"\"\n"
            f"        try:\n"
            f"            result = {call}\n"
            f"        except Exception:\n"
            f"            pass  # smoke test — only verifies no import-time error\n"
        )

    @staticmethod
    def _class_test(cls: ast.ClassDef) -> str:
        return (
            f"    def test_{cls.name}_instantiable(self):\n"
            f"        \"\"\"Smoke-test: {cls.name} can be instantiated.\"\"\"\n"
            f"        try:\n"
            f"            obj = {cls.name}()\n"
            f"            self.assertIsNotNone(obj)\n"
            f"        except Exception:\n"
            f"            pass  # smoke test only\n"
        )

    # ── Execution ──────────────────────────────────────────────────────────

    def run_tests(self, source: str, timeout: int = 15) -> Dict[str, Any]:
        """Generate tests for *source* and execute them in a subprocess.

        Returns a result dict with keys:
          ``passed``, ``failed``, ``errors``, ``output``, ``success``.
        """
        test_source = self.generate_tests(source)
        run_result  = _executor.run_code(test_source, timeout=timeout)

        passed = failed = 0
        if run_result["success"]:
            import re
            m = re.search(r"Ran (\d+) tests?", run_result.get("stderr", ""))
            if m:
                passed = int(m.group(1))
        else:
            failed = 1

        return {
            "passed":  passed,
            "failed":  failed,
            "errors":  run_result.get("error", ""),
            "output":  (run_result.get("stdout", "") or run_result.get("stderr", ""))[:500],
            "success": run_result["success"],
        }

    # ── Streaming ──────────────────────────────────────────────────────────

    def test_and_stream(
        self, source: str, timeout: int = 15
    ) -> Generator[Dict[str, Any], None, None]:
        """Run tests and yield agent-bus progress events."""
        yield {"type": "code_testing", "message": "🧪 Generating test suite…"}
        result = self.run_tests(source, timeout=timeout)
        if result["success"]:
            yield {
                "type":    "code_testing",
                "message": f"✓ Tests passed ({result['passed']} test(s))",
            }
        else:
            yield {
                "type":    "code_testing",
                "message": f"✖ Tests failed: {result['errors'][:200]}",
            }
        if result["output"]:
            yield {"type": "tool_result", "message": result["output"]}
